CREATE TABLE IF NOT EXISTS physicians (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    address VARCHAR(250) NULL,
    phone_number VARCHAR(100) NULL,
    expertise VARCHAR(100) NULL,
    consultation_time VARCHAR(100) NULL,
    created_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS patients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL,
    age INT(10) NULL,
    phone_number VARCHAR(100) NULL,
    address VARCHAR(250) NULL,
    created_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS appointments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    patient_id VARCHAR(250) NOT NULL,
    physician_id VARCHAR(250) NOT NULL,
    treatment_type_id VARCHAR(100) NOT NULL,
    time VARCHAR(100) NULL,
    room VARCHAR(100) NULL,
    note VARCHAR(250) NULL,
    created_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS treatment_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    created_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at VARCHAR(100) NULL DEFAULT CURRENT_TIMESTAMP
)
